devonfw/IDEasy

cli/src/main/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/environment/VariableLine.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandletTest.java
For #5:
* fixed EnvironmentCommandlet to properly normalize path values for Windows or Bash/MSys
* fixed EnvironmentCommandlet to also export PATH properly
* extended JUnit to cover the bug cases
=> #5: Fixed EnvironmentCommandlet

cli/src/main/java/com/devonfw/tools/ide/environment/AbstractEnvironmentVariables.java, cli/src/main/java/com/devonfw/tools/ide/environment/EnvironmentVariables.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java, documentation/pom.xml
* avoid resolving unnecessary variables (I was a little confused if trace logging is enabled by all the massive variable resolvings)
* workaround for intellij complaining about documentation module
=> small improvements

cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java
We have copied the logic to extract MSI files from our bash scripts. There we had to escape slashes due to some `bash` specific behavior. Now in Java the slashes do not need to be escaped and therefore we must only use single slashes to make it work properly.
=> #87: changed args for msiexec from double to single slash

cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java
When we extract an MSI file with `msiexec` for whatever reason that creates a copy of the MSI file in the target folder.
We never found a CLI option to prevent `msiexec` from doing this. Therefore we just have to delete that copied MSI file afterwards.
However, the code to delete it was bug and that is now fixed with this PR.
=> #89: fix deletion of the copied msi file

cli/src/test/java/com/devonfw/tools/ide/tool/UrlUpdaterTest.java, pom.xml
We had AssertJ version `2.6.0` that was entirely outdated and caused errors with Java17:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private ... accessible: module java.base does not "opens java.util" to unnamed module @7fbe847c
```
This is fixed with the update so we can use `SoftAssertions` and other modern features of AssertJ.
As AssertJ renamed some assertion methods for `java.time.*`, I had to fix a test and rename the method calls.
=> Update AssertJ to 3.24.2

cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java, cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/Eclipse.java
Addresses: #85 
I have found a solution to the issue #85. The order of the executing files is now in the same order as requested by the issue. But in order to do so, I had to change the interface of the executable() method, I had to add the String tool so that the tool name is passed to this method as an argument, in order to work with the name and the extension of the tool. Since I changed the interface, I had to make small changes to the Eclipse.java class as well, and as far as I tested it works correctly. 
If this solution is not clean, I have another option in mind, but that would require that we keep the getToolBinary() method and make changes to it. I am keeping this PR as a draft until it is decided that it is a correct solution.
=> #85: Fixed the executing order of the tools

documentation/settings.asciidoc
Remove the link to IDE-specific documentation in dedicated documents per IDE because the IDEasy configurator replaces the IDE-specific commandlets, and the IDE specific usage is now maintained in the configurator documentation.
=> remove link to cmdlet docs because onfigurator replaces cmdlets

.github/workflows/build-pr.yml, .github/workflows/build.yml, pom.xml
closes #146 implement automated coverage tool
Jacoco has been added 
Coverall has been added to the GitHub workflow, to be used in PRs
Some Steps are needed to activate Coverall:
(Documentation can also be found on the Coveralls [docu page ](https://docs.coveralls.io/app-notifications#pull-request-comments))
=> #146 Implement automated coverage tools

cli/src/main/java/com/devonfw/tools/ide/version/BoundaryType.java, cli/src/main/java/com/devonfw/tools/ide/version/VersionRange.java, cli/src/test/java/com/devonfw/tools/ide/version/VersionRangeTest.java
Improvement for Version Range (#158, #159):
* Consistency (min = null means negative infinity and requires leftExclusive, max = null means positive infinity and requires rightExclusive, min must not be greater than max)
* Syntax "[min>max]" does not really make sense (as it turns out this seems to come from https://github.com/devonfw/ide/issues/1054) and I changed `>` to `,` what is rather common (same in Maven, etc.).
* Improved maintainability of code
=> #158: improved VersionRange

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java, cli/src/main/java/com/devonfw/tools/ide/version/VersionSegment.java
=> #6: fix git hangs via non interactive invocation

cli/src/main/java/com/devonfw/tools/ide/tool/GlobalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
Fixes #183.  `isInstalledVersion()` was only used once and caused the duplicate msg if the tool was already installed.
=> #183: removed isInstalledVersion()

cli/src/main/java/com/devonfw/tools/ide/tool/jmc/Jmc.java, cli/src/test/java/com/devonfw/tools/ide/tool/Jmc/JmcTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/jmc/JmcTest.java, cli/src/test/resources/ide-projects/_ide/urls/jmc/jmc/8.3.0/linux_x64.urls, cli/src/test/resources/ide-projects/_ide/urls/jmc/jmc/8.3.0/mac_x64.urls, cli/src/test/resources/ide-projects/_ide/urls/jmc/jmc/8.3.0/windows_x64.urls
Fixes: #209 
This is a quick fix for the failure of the CI build.  In this PR is just the port number for JMC installation changed, from 1111 to 1112.
Another generally better solution is in investigation and will be implemented soon.
=> #209: Quick Fix for CI build failure

cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
Fixes: #225 by just adding a `return;` if the file is a symlink (it is then deleted and doesen't need to be moved).
=> #225: Return statement in backup() function in case of symlinks

cli/src/test/java/com/devonfw/tools/ide/repo/ToolRepositoryMock.java
improve logging of ToolRepositoryMock introduced with PR #238 as suggested by @ndemirca
=> #238: improve logging of ToolRepositoryMock as suggested by ndemirca

cli/src/main/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandlet.java
=> #254-1: removed duplication of export PATH environment variable in log

cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
Fixes: #264
Fixes: #230 
After extensive research and several attempts, it's evident that the reported issue isn't a bug but rather a result of **using devon instead of ideasy** while installing new tools. For instance:
The problem we were getting was that the moving of the installed software directory fails because of the windows file lock on the directory, e.g.` java.lang.IllegalStateException: Failed to move D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-03-22\java_17-13-29`.
This issue specifically arises when the tools are installed using 'devon' (**_as a directory_**) instead of 'ideasy' (**_as a junction_**).
When installed with 'ideasy', the file lock automatically applies to the target path of the junction `IDE_ROOT/_ide/software/default/...`, …
=> #264: prevent Windows file lock

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/step/Step.java, cli/src/main/java/com/devonfw/tools/ide/step/StepImpl.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeContextTest.java, cli/src/test/java/com/devonfw/tools/ide/log/IdeSlf4jLogger.java, cli/src/test/java/com/devonfw/tools/ide/step/StepTest.java
Fixes #293:
* Replaced the assertion that a `Step` that already ended should not end again with a warning
* allow the `Step` to end again but avoid inconsistent transition from ERROR to SUCCESS
* changed `LocalToolCommandlet` to call `postInstall()` before `step.success`
=> #293: log warning instead of assertion in Step for robustness

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
Fixes #296. 
InetAddress.isReachable() seems to require root privileges to run properly on unix. 
Solution not tested on MacOS.
=> #296 Replace InetAddress.isReachable with alternative

cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmUrlUpdater.java
Fixes #435. 
While a rewrite of `NpmUrlUpdater` might be necessary to not use `WebsiteUrlUpdater` to parse versions from JSON, this provides a quick fix to additionally make versions 10.0.0, 10.1.0, 10.2.0, 10.2.1, 10.2.2, **10.2.3**, 10.2.4, 10.2.5, 10.3.0, 10.4.0, 10.5.0, 10.5.1, 10.5.2, 10.6.0, 10.7.0, 10.8.0, and 10.8.1 of npm available.
=> #435 Fix version pattern for NpmUrlUpdater

cli/pom.xml
Fixes: #337 
Implements:
* removed -march=native (because builds were not working)
=> #337: removed march=native

documentation/LICENSE.adoc
Addition to #182, which has been closed by #388. 
Adds the required license of pgAdmin to the documentation.
=> #182 Addition: missing license for pgAdmin

cli/src/main/java/com/devonfw/tools/ide/version/VersionSegment.java, cli/src/test/java/com/devonfw/tools/ide/version/VersionRangeTest.java
Closes #489. 
Fixes the issue, now ensures that "22_1 > 22", while still "22_1 < 22.1".
=> #489: Fix separator comparison

cli/src/main/java/com/devonfw/tools/ide/commandlet/HelpCommandlet.java, cli/src/main/resources/nls/Help.properties, cli/src/main/resources/nls/Help_de.properties
Closes #308. The output of ide help now looks as follows: 
```
ide> help
__       ___ ___  ___
\ \     |_ _|   \| __|__ _ ____ _
> >     | || |) | _|/ _` (_-< || |
/_/ ___ |___|___/|___\__,_/__/\_, |
|___|                       |__/
Current version of IDE is SNAPSHOT
Usage: ide [option]* [[commandlet] [arg]*]
Available commandlets:
--version      Print the version of IDEasy.
build          Runs a build job with given arguments.
complete       Internal commandlet for bash auto-completion.
create         Create a new IDEasy project.
env            Print the environment variables to set and export.
get-edition    Get the edition of the selected tool.
get-version    Get the version of the selected tool.
help           Prints this help.
install        Install the selected tool.
list-editions …
```
=> #308 Group commandlets into non-tool and tool

cli/src/main/java/com/devonfw/tools/ide/tool/CustomToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/node/Node.java
the method installTool (which is the old installInRepo) now performs the installation for both cases (in software repo or directly in software folder based on the return value of the method isIgnoreSoftwareRepo).
closes #352
=> #352: implemented new design for tools like python and node

.editorconfig
prevent that IntelliJ formatter removes blank lines from `*.properties` files.
=> added properties formatting to .editorconfig

cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java, cli/src/test/java/com/devonfw/tools/ide/tool/mvn/MvnTest.java, cli/src/test/resources/ide-projects/mvn/project/home/environment.properties
Fixes: #463 
Implements:
* added fallback to USER_HOME for mvn repository
* added new testMavenRepositoryPathFallsBackToUserHome to MvnTest
* added environment.properties to mvn test resources (required for proper simulation of USER_HOME)
=> #463: Set default Maven m2 repository location back to user home

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
=> #527: fix for NPE in findIdeRoot

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
fixes #527 (fix of fix from PR #528)
In sprint review we hit this again and I finally fixed it properly.
=> #527: fix of fix

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContext.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java, cli/src/test/java/com/devonfw/tools/ide/context/GitContextMock.java, cli/src/test/java/com/devonfw/tools/ide/context/GitContextTest.java
fixes #570 
Also include small cleanup from #467 and small partial fix of #525
=> #570: fix git rev parse error if not in project

cli/src/main/java/com/devonfw/tools/ide/commandlet/RepositoryCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContext.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java, cli/src/main/java/com/devonfw/tools/ide/context/GitOperation.java, cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java, cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java, cli/src/test/java/com/devonfw/tools/ide/context/GitContextMock.java, cli/src/test/java/com/devonfw/tools/ide/context/GitContextTest.java, cli/src/test/java/com/devonfw/tools/ide/context/GitOperationTest.java
fixes #585 
* check if FETCH_HEAD does not exist
* also properly handle force mode (always fetch)
* add debug logging if fetch was skipped
* make code more readable
* extracted generic code pattern to `GitOperation` that is now reused for `fetchIfNeeded` and `pullOrCloneIfNeeded`.
* the method `pullOrCloneIfNeeded` had the same bug with force mode that is now also fixed.
* added JUnit test to test all variants
=> #585: fix if FETCH_HEAD does not exist, also fixed behavior on force mode

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java, cli/src/main/java/com/devonfw/tools/ide/process/EnvironmentContext.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java, cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/context/ProcessContextGitMock.java
fixes #556 
* add `withPathEntry(Path)` method for future implementations of `setEnvironment` methods
* add ability to create a modified `SystemPath` via `withPath` method
* change ProcessContext to track PATH changes and apply them only in `run` method
* also move the code to find the binary executable to `run` method using the final PATH
* improved logging
* changed `ToolCommandlet` to simplify after this "bug" has been fixed
=> #556: update PATH on pc run

cli/src/test/java/com/devonfw/tools/ide/commandlet/HelpCommandletTest.java
On my machine an update caused the default local to be German and then `HelpCommandletTest` fails.
Tests must never dependent on system specific settings such as locale, timezone, encoding, etc.
=> fix HelpCommandletTest to work locale insensitive

cli/src/main/java/com/devonfw/tools/ide/io/AbstractIdeProgressBar.java, cli/src/main/java/com/devonfw/tools/ide/io/IdeProgressBar.java, cli/src/test/java/com/devonfw/tools/ide/io/IdeProgressBarConsoleTest.java
fixed #618 (not yet)
* cleanup test and removed obvious nonsense
* still the `testProgressBarStyleSwitchOnNonWindows` that testes linux on Windows seems to cause 2 Minutes of think-time if called from a real shell. My question is what is the benefit of this if the costs are that high.
* This PR is a small but nice improvement. However, it does not solve the problem described in #618
=> #618: improve IdeProgressBarConsoleTest

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/cli/CliArgument.java, cli/src/main/java/com/devonfw/tools/ide/tool/androidstudio/AndroidStudio.java, cli/src/main/java/com/devonfw/tools/ide/tool/intellij/Intellij.java, cli/src/test/java/com/devonfw/tools/ide/cli/CliArgumentTest.java
Fixes #623 
Intentionally I did not change Eclipse from prepend to append since I think this is desired here.
=> #623: fix CliArgument prepend/append

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/UpdateCommandletTest.java, cli/src/test/resources/ide-projects/update/repository/java/java/default/bin/java, cli/src/test/resources/ide-projects/update/repository/mvn/mvn/default/bin/mvn
Fixes: #628 
Implements:
* added catch of exceptions for ToolCommandlet installations
* converted steps to try-with-resources
* added new test for failed update substeps
* added mvn and java repositories to update test-project
=> #628: Fixed update fails on first error

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
fixes #588
* reload `IdeContext` (variables) after settings are cloned and conf folder is initialized.
=> #588: reload context after clone settings

cli/pom.xml, cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/MergeStrategy.java, cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/XmlMerger.java, cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/matcher/ElementMatcher.java, cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/matcher/IdComputer.java, cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/model/MergeElement.java, cli/src/test/java/com/devonfw/tools/ide/merge/XmlMergerTest.java, cli/src/test/resources/xmlmerger/id-fallback/result.xml, cli/src/test/resources/xmlmerger/id-fallback/source.xml, cli/src/test/resources/xmlmerger/id-fallback/target.xml
fixes #640 
* verification and error on empty merge:id must only happen before `IdComputer` shall be constructed.
* improved XmlMergerTest
* extended `id-fallback` test as already suggested before by @jan-vcapgemini in PR #622 for bug #621 (due to my "ignorance" we have not immediately found this bug).
=> #640: fix xml merger if merge:id is omitted for repated element

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContext.java, cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java, cli/src/main/java/com/devonfw/tools/ide/process/ProcessResultImpl.java, cli/src/main/java/com/devonfw/tools/ide/step/StepImpl.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/UpdateCommandletTest.java, cli/src/test/java/com/devonfw/tools/ide/context/GitContextMock.java, cli/src/test/java/com/devonfw/tools/ide/process/ProcessContextImplTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/androidstudio/AndroidStudioTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/intellij/IntellijTest.java
* fixed NPE I got when offline because ProcessResult.out was null
* improved GitContext - instead of retrieving all branches and remotes and looking for `*` we can simply get current branch and default remote to simplify.
* instead of checking online status 5 or more times via expensive remote operation, simply store the result
* improve step success logging that was slightly confusing
=> various improvements (git, processContext, step success)

cli/pom.xml
Fixes: #655 
This PR updates the versions of maven libraries that are detected by CVE scan.
Fixes: https://nvd.nist.gov/vuln/detail/CVE-2024-26308
=> #655: Update Versions of Common Compress and XML-Unit Core

cli/src/test/java/com/devonfw/tools/ide/tool/java/JavaUrlUpdaterMock.java, cli/src/test/java/com/devonfw/tools/ide/tool/java/JavaUrlUpdaterTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/npm/NpmJsonUrlUpdaterTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/npm/NpmUrlUpdaterMock.java, cli/src/test/resources/integrationtest/NpmJsonUrlUpdater/npm-version.json
fixes #223
still found wiremock tests with fixed port numbers and fixed them to use dynamic port
=> #223: use only dynamic ports for wiremock

documentation/DoD.adoc
=> #675: Fix typos in DoD asciidoc

cli/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java
Quickfix for odd API bug I found during code-review.
=> Update ProcessContext.java: fixed crazy bug with pointless vararg for List

cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/Eclipse.java
eclipse plugins need `plugin_url`.
=> Update Eclipse.java: plugin url needed

cli/src/main/java/com/devonfw/tools/ide/commandlet/Commandlet.java, cli/src/main/java/com/devonfw/tools/ide/repo/DefaultToolRepository.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/graalvm/GraalVm.java, cli/src/main/java/com/devonfw/tools/ide/url/model/file/json/ToolDependencies.java
fixes #673 
* One fix was also in ide-urls [commit](https://github.com/devonfw/ide-urls/commit/a33c2eee78a489df424ff94be071ec6fe25ac09c)
* The main fix here was that `environmentContext` was not passed to recursive `install` method (in such situations a NPE would have been preferred that is prevented by the EMPTY instance of EnvironmentContext)
* And for the record: IntelliJ has a severe flaw. When you run this use-case from IntelliJ, there is no way to stop the process in Intellij. The only way to end it and being able to start another run is to find and kill the process manually in task manager (what requires ProcessExplorer). This works flawless in Eclipse.
=> #673: fixed tomcat and improved logging

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/repo/DefaultToolRepository.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/url/model/file/UrlDependencyFile.java, cli/src/main/java/com/devonfw/tools/ide/url/model/file/json/ToolDependencies.java, cli/src/main/java/com/devonfw/tools/ide/url/model/folder/AbstractUrlToolOrEdition.java, cli/src/main/java/com/devonfw/tools/ide/url/model/folder/UrlEdition.java, cli/src/main/java/com/devonfw/tools/ide/url/model/folder/UrlTool.java, cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeTestContext.java, cli/src/test/java/com/devonfw/tools/ide/context/IdeSlf4jContext.java, cli/src/test/java/com/devonfw/tools/ide/context/IdeTestContextMock.java, cli/src/test/java/com/devonfw/tools/ide/tool/eclipse/EclipseTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/intellij/IntellijTest.java, cli/src/test/java/com/devonfw/tools/ide/url/model/AbstractUrlModelTest.java, cli/src/test/java/com/devonfw/tools/ide/url/model/file/UrlStatusFileTest.java, cli/src/test/java/com/devonfw/tools/ide/url/model/file/json/ToolDependenciesTest.java, cli/src/test/resources/urls/mvn/dependencies.json, cli/src/test/resources/urls/tomcat/dependencies.json, cli/src/test/resources/urls/tomcat/tomcat/dependencies.json
fixes #727
* allow fallback to edition independent dependencies.json
* added test since there was no test for this
* improve test-infrastructure
=> #727: allow fallback to edition independent dependencies.json

cli/src/main/java/com/devonfw/tools/ide/tool/mvn/Mvn.java
Fixes: #744 
This quick bug fixes the MAVEN_ARGS variable. The reason for the bug was a missing whitespace that separates the arguments.
=> #744: Fix MAVEN_ARGS by separating arguments

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/tool/GlobalToolCommandlet.java, cli/src/main/package/setup
**Fixes**: #415 
**implements**:
- Added a method that will inform the user for what process he will need to enter his sudo- password
=> #415: log command before sudo pw

cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
fixes #754 
but only as quickfix.
For a "once and forever" fix, we might need to logger that is initially collecting log statements and only activated if the commandlet to run is determined and the apply the collected log events.
We can still discuss how to solve this properly.
However, for our release the current quickfix would be enough and we can merge this and leave #754 open.
=> #754: quickfix via lazy init

cli/src/main/package/functions, cli/src/main/package/setup
fixes #810
added warning message to setup explaining that a new shell needs to be started to use IDEasy:
```
$ unset -f ide
$ rm /d/projects/_ide/bin/ide
$ ide help
bash: /d/projects/_ide/bin/ide: No such file or directory
$ source setup
Setting up IDEasy in /d/projects/_ide
Configuring IDEasy in /c/Users/hohwille/.bashrc.
Configuring IDEasy in /c/Users/hohwille/.zshrc.
ATTENTION: IDEasy has been setup for your shells but you need to start a new shell to make it work.
Only if you invoked this setup script by sourcing it, you are able to run 'ide' and 'icd' commands without starting a new shell.
$ ide help
__       ___ ___  ___
\ \     |_ _|   \| __|__ _ ____ _
> >     | || |) | _|/ _` (_-< || |
/_/ ___ |___|___/|___\__,_/__/\_, |
|___|                       |__/
Current version of IDE is …
```
=> #810: added warning message to setup 

cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java
Fixes: #840 
Implements:
* added fallback to origin if no remotes were found
=> #840: fixed fetch determine remotes

cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java, cli/src/main/java/com/devonfw/tools/ide/io/PathCopyListener.java
cleanup of code style after PR #835
=> #799: clean code improvements

cli/src/main/java/com/devonfw/tools/ide/commandlet/CommandletManagerImpl.java, cli/src/main/java/com/devonfw/tools/ide/property/KeywordProperty.java
fixes #834
In PR #876 I did not test well enough.
It worked initially with `--help` and `help` but then I did some cleanup that was also good but stopped the long options (`--help` and `--version` from working). With this PR it is finally fixed.
=> #834: bugfix for long options of commandlets

CHANGELOG.adoc, cli/src/main/package/bin/ide.bat
Fixes: #894 
This PR fixes ide.bat to print the correct output when an error occurs or ideasy is initialized.
=> #894: Fix ide.bat printing for initialization and error output

cli/src/main/package/setup
with #779 we have now functions getting sourced from `.bashrc` and that script already triggers an initialization.
As a leftover we still had the invocation of `ide init` in `.bashrc` causing a duplicate init that does not make any sense.
Also we might remove `init` as valid arg for `ide` command/function and therefore do not want to have such leftovers in `.bashrc` files of our users (from previous releases).
Having just a single line in `.bashrc` that will stay stable forever is the perfect solution.
=> avoid duplicated initialization of IDEasy

cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
Test-quickfix introduced by PR #903
=> #903: fix test to avoid modification in src/test/resources causing other tests to turn red as side effect

cli/src/main/java/com/devonfw/tools/ide/commandlet/StatusCommandlet.java
Closes https://github.com/devonfw/IDEasy/issues/942
* Added check to verify if devon.properties file exists 
* Warning is only logged when file exists
=> #942: Added check for existence of devon.properties file

documentation/usage.adoc
The master branch does not exist in the upstream IDEasy repository.
=> Update branch name from master to main in usage.adoc

cli/src/main/package/functions
follow up fix of #935
do not make `ide` command without args call `ideasy status`.
User shall explicitly call `ide status` to get the status to avoid undesired log "spam".
=> #935: followup - remove implicit status invocation

cli/src/main/package/setup
fixes #914
fixes #940 
Before:
```
Setting up IDEasy in D:\projects\_ide
IDEasy is already added to your PATH.
Found bash at C:\Program Files\Git\bin\bash.exe
"C:\Program Files\Git\bin\bash.exe" -l -c "cd \"D:\projects\_ide\";./setup"
Setting up IDEasy in /d/projects/_ide
2025.01.001-beta-01_21_02-SNAPSHOT
Created /home/runner/work/IDEasy/IDEasy/cli/pom.xml
Configuring IDEasy in /c/Users/hohwille/.bashrc.
Created /home/runner/work/IDEasy/IDEasy/cli/pom.xml
Configuring IDEasy in /c/Users/hohwille/.zshrc.
ATTENTION: IDEasy has been setup for your shells but you need to start a new shell to make it work.
Only if you invoked this setup script by sourcing it, you are able to run 'ide' and 'icd' commands without starting a new shell.
Setup of IDEasy completed
Drücken Sie eine beliebige Taste . …
```
=> #914: #940: quickfix to print correct filename

documentation/advanced-tooling-windows.adoc
The most obvious errors have been fixed. 
Hope it helps.
=> #984: windows documentation: typo's correction

documentation/pom.xml
See #958 
Since we only want to generate PDF, we do not need epub and better remove it so we do not need the upgrade #958 and all future upgrades that may come.
=> #958: instead of upgrade better remove epub since we do not need it

CHANGELOG.adoc, cli/pom.xml
Improvement for #599 
Currently our windows-x64 releases do not even run on windows@arm via emulation.
This PR should fix this.
=> #599: graalvm compatibility mode to make x86-64 releases work on arm-64

cli/src/main/java/com/devonfw/tools/ide/git/repository/RepositoryCommandlet.java
In the Story-Review of #990 we found a simple logging bug causing:
```
Invalid log message with 2 argument(s) but less placeholders: Ignoring repository {} - use --force to rerun setup.
Ignoring repository base - use --force to rerun setup.
```
The first of the two log messages indicates a bug in our code:
https://github.com/devonfw/IDEasy/blob/e4b0f98b8cef4ed2f3814525c8409e9f6d570d85/cli/src/main/java/com/devonfw/tools/ide/git/repository/RepositoryCommandlet.java#L103
It is printed in red for every repository what is rather annoying.
Since fix is trivial and no risc, we will include it into our release.
=> #954: fix log message

cli/src/main/java/com/devonfw/tools/ide/version/VersionRange.java, cli/src/test/java/com/devonfw/tools/ide/version/VersionRangeTest.java
#1019 
"blank" strings should be treated as "empty" strings, rather than causing errors
=> 1019: extra spaces should not cause problem in version range expression

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java, cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java, cli/src/main/java/com/devonfw/tools/ide/merge/PropertiesMerger.java, cli/src/main/java/com/devonfw/tools/ide/tool/ide/IdeToolCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/merge/DirectoryMergerTest.java, cli/src/test/java/com/devonfw/tools/ide/tool/ide/IdeToolCommandletTest.java, cli/src/test/resources/ide-projects/intellij/project/home/.ide/intellij/workspace/setup/.intellij/config/idea.key, cli/src/test/resources/ide-projects/intellij/project/home/.ide/workspace/update/user.properties, documentation/.asciidoctorconfig, documentation/DoD.adoc, documentation/configuration.adoc, documentation/configurator.adoc, documentation/features.adoc, documentation/software.adoc, documentation/workspaces.adoc
fixes #982
* implemented story #982 
* added to changelog
* updated and reworked documentation
* Added/extended test to verify new functionality
=> #982: ability for user specific workspace configuration templates

cli/src/main/java/com/devonfw/tools/ide/version/VersionRange.java, cli/src/test/java/com/devonfw/tools/ide/version/VersionRangeTest.java
fixes #1034
replacement for PR #1035
=> #1034: proper fix of VersionRange.contains for version patterns

cli/src/main/java/com/devonfw/tools/ide/commandlet/StatusCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/StatusCommandletTest.java
Fixes #1060
- Check "checkIfUpdateIsAvailable" also if execution folder is the projects folder (e.g. "c:\projects") 
- Warning that IDE_HOME is not set if execution folder is the projects folder (e.g. "c:\projects")
=> #1060: ide status runs correct in folder c:/projects (d:/project)

documentation/advanced-tooling-mac.adoc
- Fixed typo in advanced-tooling-mac.adoc
Previous PR was closed because of "Merging is blocked"-issue. https://github.com/devonfw/IDEasy/pull/1075
=> #1066 : Fixed typo in documentation

.github/workflows/nightly-build.yml, .github/workflows/release.yml
Fixes: #1087 
This PR fixes the missing include of `ideasy.exe` in the MSI build process for the `nightly build `and for the `release ` workflow.
=> #1087: Fix MSI Build Job in GitHub Workflows

cli/pom.xml, windows-installer/Package.wxs
Fixes: #1087 
This PR implements 
- a workaround for the MSI Installation Setup by executing `setup.bat -b` instead of `ideasy.exe -f install`
- add hardcoded `windows-64` in filename
- change uninstall path and ignore return
=> #1087: Fix MSI Installation with setup.bat workaround

.github/workflows/nightly-build.yml, .github/workflows/release.yml
improvement for #420 
since we copy the `package` content in a script code from the github action, the filters configured for assembly do not apply and linux and mac content gets included in windows MSI.
https://github.com/devonfw/IDEasy/blob/7fa23c7e687fe5015fd7149266cf4b7b598c463f/cli/src/main/assembly/release-win-x64.xml#L27-L28
=> #420: exclude mac and linux content from MSI

cli/pom.xml
improvement for #420 
have os and architecture (`windows-x64`) in filename of MSI file.
=> #420: ensure os and architecture in filename

windows-installer/Package.en-us.wxl, windows-installer/Package.wxs, windows-installer/README.adoc, windows-installer/WixUI_IDEasySetup.wxs
Fixes: #1095 
This PR fixes the drive selection to install IDEasy into the user home folder or select a drive and the installation will be in e.g `C:\projects`
Further, the UI is adapted for the selection and `IDE_ROOT` is set during the installation. 
Tested with msi artifact from this run: https://github.com/alfeilex/IDEasy/actions/runs/13580678832
=> #1095: Fix MSI Installation Drive Selection

.github/workflows/release.yml
fixes #420
Fixes msi download url, added missing `-windows-x64` to github action release workflow.
=> #420: Fix msi download url

cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/EclipseUrlUpdater.java
fixes #1052
add official eclipse download URL since other configured mirrors are outdated or seem obsolete
=> #1052: add official eclipse download URL

CHANGELOG.adoc, windows-installer/Package.wxs
fixes #1111
simplified and minimized alternative to PR #1119
Currently testing via GHA on my fork.
https://github.com/hohwille/IDEasy/actions/runs/13768602112/job/38501245151
MSI: https://github.com/hohwille/IDEasy/actions/runs/13768602112/artifacts/2723410455
Test negative :x: Installer hangs, license agreement not created.
OK. Stupid me, I followed the story suggestion that was pointing to the line with the uninstallation instead of the installation.
Fixed. Next try:
https://github.com/hohwille/IDEasy/actions/runs/13769078901/job/38502875404
MSI: https://github.com/hohwille/IDEasy/actions/runs/13769078901/artifacts/2723565003
Test positive: :white_check_mark: works now.
=> #1111: create license agreement file

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/commandlet/UpgradeMode.java, cli/src/main/java/com/devonfw/tools/ide/version/VersionPhase.java, cli/src/test/java/com/devonfw/tools/ide/version/VersionIdentifierTest.java
Fixes: #1159
**Implements**
* changed UpgradeMode SNAPSHOT to *!=SNAPSHOT
* added beta-snapshot to VersionPhase SNAPSHOT
* added tests for unstable version and snapshot detection
=> #1159: Fixed SNAPSHOT version handling

.github/workflows/update-urls.yml
This PR fixes: #1115 
Switch from comparing `$(git status -z)` with an empty string to using `grep -q .` to check for any output. That's because `-z` uses a null byte delimiter to separate filenames in the printed output. This leads to warnings in the logs because command substitution `$(...)` can not handle null bytes as input
=> #1115: Fix Git Action Warnings in Url Updater

CHANGELOG.adoc, windows-installer/WixUI_IDEasySetup.wxs
Fixes: #1233
This PR increases the dropdown width of drive selection in MSI installer. The reason for that change is that with scaling set to 100%, the dropdown field was too narrow.
=> #1233: Fix dropdown width of drive selection in MSI installer

CHANGELOG.adoc, cli/src/main/package/bin/ide.bat
Fixes #1252 
Implemented: 
- an echo that warns to use (git-)bash with ideasy when using CMD or PowerShell
=> #1252 Warning when using CMD or PowerShell

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java
Fixes: #1271
**Implements**
* added redirectInput INHERIT if ProcessMode is not DEFAULT_CAPTURE
=> #1271: Fixed aws input not being processed

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/environment/EnvironmentVariablesSystem.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandletTest.java, cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeTestContext.java, cli/src/test/java/com/devonfw/tools/ide/environment/EnvironmentVariablesTest.java, cli/src/test/resources/ide-projects/environment/project/conf/mvn/settings.xml, cli/src/test/resources/ide-projects/environment/project/home/environment.properties
* implemented #351
* ignore all environment properties relevant to IDEasy except for PATH, HOME, and IDE_ROOT
* added test
* improved test-infrastructure to behave more realistic using `EnvironmentVariablesSystem` that was otherwise mocked by a different class.
---
=> #351: prevent environment variables from other project causing side-effects

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/commandlet/InstallPluginCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/log/AbstractIdeSubLogger.java, cli/src/main/java/com/devonfw/tools/ide/log/IdeSubLogger.java, cli/src/main/java/com/devonfw/tools/ide/step/Step.java, cli/src/main/java/com/devonfw/tools/ide/step/StepImpl.java, cli/src/main/java/com/devonfw/tools/ide/tool/DelegatingToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/GlobalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/docker/Docker.java, cli/src/main/java/com/devonfw/tools/ide/tool/ide/IdeToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/mvn/Mvn.java, cli/src/main/java/com/devonfw/tools/ide/tool/pgadmin/PgAdmin.java, cli/src/main/java/com/devonfw/tools/ide/tool/plugin/PluginBasedCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/UpdateCommandletTest.java, cli/src/test/java/com/devonfw/tools/ide/step/StepTest.java
* Remove `AutoClosable` from `Step`
* Rewrote JavaDoc of `Step`
* Fixed all code using `try-with-resource` on `Step`
* Fixed the actual bug that several steps could fail causing the entire process to fail immediately.
* Fixed the case where maven settings is to be created but no security config file is present.
---
=> #1332: fixed bug pattern, proper Step usage, allow running tool if plugin failed

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/tool/ide/IdeToolCommandlet.java, cli/src/test/integration-tests/install-intellij.sh, cli/src/test/java/com/devonfw/tools/ide/tool/intellij/IntellijTest.java
* configureWorkspace on install of IDE so that IJ properties file is created before plugin installation
---
=> #1361: fix IDE (IntelliJ) plugin installation

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java, cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java, cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java, cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeTestContext.java
* Log warning if IDE_ROOT is not sane (undefined, wrong case, not matching parent of IDE_HOME)
* Auto-repair IDE_ROOT if not sane to prevent follow up errors.
---
=> #1340: proper fix if IDE_ROOT is not sane

CHANGELOG.adoc, cli/src/main/package/bin/ide.bat
* Added quotes to the ideasy call inside the for loop in ide.bat
---
=> #1309: Fixed ide.bat splitting IDE_OPTIONS

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/commandlet/StatusCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java, cli/src/test/java/com/devonfw/tools/ide/commandlet/StatusCommandletTest.java
* the current version of IDEasy will be printed even when offline
* also print the operating system when offline
Before:
```
Skipping git fetch on C:\Users\<user>\projects\IDEasy\settings because we are offline.
IDE_ROOT is set to C:\Users\<user>\projects
IDE_HOME is set to C:\Users\<user>\projects\IDEasy
You are offline. Check your internet connection and potential proxy settings.
Your settings are up-to-date.
Check for newer version of IDEasy is skipped due to no network connectivity.
Successfully completed ide (status)
```
After:
```
Skipping git fetch on C:\Users\<user>\projects\Test\settings because we are offline.
IDE_ROOT is set to C:\Users\<user>\projects
IDE_HOME is set to C:\Users\<user>\projects\IDEasy
You are offline. Check your internet connection and potential proxy …
```
=> #1160: IDEasy version gets printed when using ide status offline

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
* on main privacy mode has a critical bug: in case of early logging (--trace) the `privacyMap` with the replacements is created before `ideRoot` and `ideHome` is set.
* I fixed it so regular usage is now working as expected
* still looking if edge-cases can still cause the problem...
---
=> #1303: fix critical bug on early logging causing mess

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/url/model/UrlMetadata.java, cli/src/main/java/com/devonfw/tools/ide/url/model/folder/UrlVersion.java
* throw CliException instead of IllegalStateException when tool version is not supported on current OS
Can betested on Windows by running:
`ide install vscode 1.12.0`
Can be tested on Linux by running:
`ide install az 2.52.0`
---
=> #1387: throw CliException when tool version not supported for OS

windows-installer/Package.wxs
* escape ampersand in wix toolkit XML
---
=> #1486: fixed MSI build

CHANGELOG.adoc, cli/src/main/java/com/devonfw/tools/ide/tool/mvn/MvnBasedLocalToolCommandlet.java, cli/src/main/java/com/devonfw/tools/ide/tool/repository/MvnRepository.java
* fix actual bug that version is not resolved in mvn artifact
* fixed also ordering of mvn versions so they are in descending order as required.
---
=> #1515: fix snapshot upgrade
