devonfw/IDEasy

- cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
I teached the team never to do this bug / anti-pattern... but I ran into the pitfall myself. OMG
> OMG, never omit exception cause

- cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeContextTest.java
#5 fixed bug where assertLogMessage would only check the Warning level
> #5: fixed assertLogMessage

- cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java
I think the "have" slipped in. Correct my if I am wrong.
> Grammar in Comment ToolCommandlet.java

- cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionGetCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionListCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionSetCommandlet.java
Addresses: #79 
- Simplified multi-keyword commandlets and made usage consistent.
> #79: Simplified multi-keyword commandlets

- documentation/IDEasy-contribution-rules-and-guidelines.asciidoc
#5 using the epic, as this is a PR without Issue
added additional Information for the contribution and usage of Github.
> #5 added contributen rules and guideines

- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/EclipseJeeUrlUpdater.java
- cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/EclipseUrlUpdater.java
- cli/src/main/java/com/devonfw/tools/ide/url/updater/UpdateManager.java
> devonfw/ide#1368: added updater for eclipse jee

- cli/src/main/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/environment/AbstractEnvironmentVariables.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandletTest.java
> #254: Part 2: add missing quotation marks

- cli/src/main/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/property/VersionProperty.java
fixes #254
* PATH entries need to be normalized to MSYS syntax in case of Git-Bash
> #254: fix bash path

- documentation/IDEasy-usage.adoc
- documentation/projects.adoc
- documentation/updates.adoc
Closes #265  Repair the links for projects and updates and delete the link for scripts
> #265 Correction in IDEasy-usage.adoc

- cli/src/test/java/com/devonfw/tools/ide/context/IdeContextTest.java
Fixes: #239
Adding regex to clean PATH variable
> #239 Test for Environment Variables fails

- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/merge/DirectoryMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/FallbackMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/FileMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/TextMerger.java
- cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
- cli/src/test/java/com/devonfw/tools/ide/merge/DirectoryMergerTest.java
- cli/src/test/resources/templates/setup/.name
- cli/src/test/resources/templates/update/.name
Fixes: #154 
Implements:
* added TextMerger with `.name` extension to DirectoryMerger
* moved copy method from FallbackMerger to FileMerger
* added test to DirectoryMergerTest
> #154 Show project name in header of intellij

- cli/src/main/java/com/devonfw/tools/ide/version/IdeVersion.java
Might not fix #329 but relates to it and simplifies the code making it much easier and nicer.
If we are lucky, it may magically also fix #329 but this is not expected.
> #329: simplify version determination

- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/tool/mvn/Mvn.java
- cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
> #328: set M2_REPO variable

- cli/src/main/java/com/devonfw/tools/ide/version/VersionSegment.java
- cli/src/test/java/com/devonfw/tools/ide/version/VersionIdentifierTest.java
> #235: fix VersionIdentifier to compare java versions correctly

- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
- cli/src/main/java/com/devonfw/tools/ide/variable/VariableDefinitionPath.java
> #390:M2_REPO variable as VariableDefinitionPath

- cli/src/main/java/com/devonfw/tools/ide/completion/CompletionCandidateCollector.java
- cli/src/test/java/com/devonfw/tools/ide/completion/CompletionCandidateCollectorDefaultTest.java
> #418 Fix autocomplete of version

- .github/workflows/release.yml
> #448: fix release workflow

- cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
Fixes: #469 
Implements:
* new IDEA_PROPERTIES environment variable pointing to workspaces/main/idea.properties files
> #469: added IDEA_PROPERTIES to variables

- cli/src/main/java/com/devonfw/tools/ide/merge/TextMerger.java
Fixes: #472
Implements:
* added missing directory before file write (using ensureParentDirectoryExists)
> #472: added missing directory

- cli/src/main/java/com/devonfw/tools/ide/cli/Ideasy.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/Commandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/CompleteCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/EditionGetCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/EnvironmentCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/HelpCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionGetCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/process/ProcessResult.java
- cli/src/main/java/com/devonfw/tools/ide/property/Property.java
- cli/src/main/java/com/devonfw/tools/ide/step/StepImpl.java
> #400: fix error handling for undefined IDE_ROOT and IDE_HOME

- cli/src/main/java/com/devonfw/tools/ide/tool/intellij/Intellij.java
- cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
- cli/src/test/java/com/devonfw/tools/ide/tool/intellij/IntellijTest.java
- cli/src/test/resources/ide-projects/intellij/project/conf/ide.properties
Implements:
* added export of IDEA_PROPERTIES
* added test of existing export of IDEA_PROPERTIES in ide.properties
> #464: added export of IDEA_PROPERTIES

- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
- cli/pom.xml
Fixes: #499 
Implements:
* fixed nightly and release workflows
> #499: fix release workflow

- .editorconfig
- cli/src/main/java/com/devonfw/tools/ide/cli/CliArgument.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/Commandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/CommandletManager.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/ShellCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/common/JsonVersionItem.java
- cli/src/main/java/com/devonfw/tools/ide/common/Tag.java
- cli/src/main/java/com/devonfw/tools/ide/common/Tags.java
- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/GitContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/environment/AbstractEnvironmentVariables.java
- cli/src/main/java/com/devonfw/tools/ide/environment/EnvironmentVariables.java
- cli/src/main/java/com/devonfw/tools/ide/environment/VariableSource.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileCopyMode.java
- cli/src/main/java/com/devonfw/tools/ide/log/IdeSubLogger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/XmlMerger.java
- cli/src/main/java/com/devonfw/tools/ide/process/ProcessContext.java
- cli/src/main/java/com/devonfw/tools/ide/repo/AbstractToolRepository.java
- cli/src/main/java/com/devonfw/tools/ide/repo/ToolRepository.java
- cli/src/main/java/com/devonfw/tools/ide/step/Step.java
- cli/src/main/java/com/devonfw/tools/ide/tool/CustomToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/ToolInstallation.java
- cli/src/main/java/com/devonfw/tools/ide/tool/aws/AwsUrlUpdater.java
- cli/src/main/java/com/devonfw/tools/ide/url/model/UrlMetadata.java
fixes #465 
* Improve editorconfig by continuation indent of JavaDoc
* applied changes to JavaDoc 
* added some missing JavaDoc
> #465: improve editorconfig

- cli/src/test/java/com/devonfw/tools/ide/completion/CompleteTest.java
stepwise re-adding small changes from #424 to see if they break tests on github or not
> #424: integrate small changes

- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/test/java/com/devonfw/tools/ide/completion/IdeCompleterTest.java
last relevant change from PR #424
> #424: re-adding last relevant change

- cli/src/main/java/com/devonfw/tools/ide/cli/Ideasy.java
Fixes: #612
Implements:
* fixed URL
> #612: fixed issue URL

- cli/src/test/java/com/devonfw/tools/ide/environment/EnvironmentVariablesPropertiesFileTest.java
Fixes https://github.com/devonfw/IDEasy/pull/568/files
> fixed unittest creating a new test properties file

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/matcher/ElementMatcher.java
- cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/model/MergeElement.java
- cli/src/test/java/com/devonfw/tools/ide/merge/XmlMergerTest.java
- cli/src/test/resources/xmlmerger/id-fallback/result.xml
- cli/src/test/resources/xmlmerger/id-fallback/source.xml
- cli/src/test/resources/xmlmerger/id-fallback/target.xml
> #621: fixed ID fallback for XML merger

- cli/src/main/java/com/devonfw/tools/ide/tool/Dependency.java
- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/url/model/file/json/DependencyInfo.java
preparation for #634
change DependencyInfo to record
> #634: preparation: change DependencyInfo to record

- cli/src/main/java/com/devonfw/tools/ide/json/DependencyInfoDeserializer.java
- cli/src/main/java/com/devonfw/tools/ide/json/JsonMapping.java
- cli/src/test/java/com/devonfw/tools/ide/json/JsonMappingTest.java
fixes #634 
* added DependencyInfoDeserializer
* register it in JsonMapping
* extended test for this case.
> #634: added DependencyInfoDeserializer

- cli/src/main/java/com/devonfw/tools/ide/tool/eclipse/Eclipse.java
- cli/src/main/java/com/devonfw/tools/ide/tool/mvn/Mvn.java
- cli/src/test/java/com/devonfw/tools/ide/tool/plugin/ExamplePluginBasedCommandlet.java
addon to #652 that introduced step to plugin installation but code needs to report success/error to step now
> #652: properly report step success/error

- cli/src/main/java/com/devonfw/tools/ide/url/model/file/json/UrlStatusState.java
- cli/src/main/java/com/devonfw/tools/ide/url/updater/AbstractUrlUpdater.java
- cli/src/test/java/com/devonfw/tools/ide/tool/UrlUpdaterMock.java
- cli/src/test/java/com/devonfw/tools/ide/tool/UrlUpdaterTest.java
- cli/src/test/java/com/devonfw/tools/ide/url/report/UrlUpdaterReportTest.java
> #687: prevent checksum recheck

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/merge/DirectoryMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/FallbackMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/FileMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/JsonMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/PropertiesMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/TextMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/WorkspaceMerger.java
- cli/src/main/java/com/devonfw/tools/ide/merge/xmlmerger/XmlMerger.java
- cli/src/main/java/com/devonfw/tools/ide/step/StepImpl.java
- cli/src/main/java/com/devonfw/tools/ide/tool/ide/IdeToolCommandlet.java
> #710: make workspace configuration robust

- documentation/IDEasy-contribution-rules-and-guidelines.adoc
fixed example of external github repository reference
> Fixed external github ref example

- cli/src/main/java/com/devonfw/tools/ide/commandlet/ShellCommandlet.java
Fixes: #168 
Implements:
* Removed TODO for BuiltIns implementation
> #168: Removed BuiltIns TODO entry

- cli/src/main/package/bin/ide
- documentation/Not_supported_Cygwin.adoc
- documentation/cygwin.adoc
> #715: Cygwin not supported warning.

- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
fixes #844
ensure logging is enabled when an error occurred or CLI parameters are invalid
> #844: ensure logging is enabled when an error occurred or CLI parameters are invalid

- cli/src/main/java/com/devonfw/tools/ide/commandlet/Commandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/CommandletManagerImpl.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/HelpCommandlet.java
fixes #846 
also support alias of first keyword property in `CommandletManager.getCommandletByFirstKeyword`
> #846: fix version shortopt (-v)

- .github/workflows/nightly-build.yml
> #791: unique SNAPSHOT versions

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/property/Property.java
fixes #879
minimum fix to allow `-` as value.
> #879: allow `-` as value

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/tool/lazydocker/LazyDocker.java
> #875: fix lazydocker

- cli/src/main/java/com/devonfw/tools/ide/tool/lazydocker/LazyDocker.java
> #875: added docker error message

- cli/src/main/java/com/devonfw/tools/ide/commandlet/RepositoryCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/ShellCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/property/PathProperty.java
- cli/src/main/java/com/devonfw/tools/ide/property/RepositoryProperty.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/RepositoryCommandletTest.java
fixes #939
* fix NPE on path completion 
* implement repository completion
> #939: fix NPE on path completion and implement repository completion

- cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractVersionOrEditionGetCommandlet.java
Follow up of #898 
* adjusted tool name in error message
> #898: adjusted tool name in error message

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/UpdateCommandletTest.java
- cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeContextTest.java
> #993: create IDE start scripts

- cli/src/test/java/com/devonfw/tools/ide/tool/IdeasyCommandletTest.java
fixes #1061 
sorry for being over pragmatic and fixing the real bug outside of PR.
This PR adds the test changes so we cannot run into the bug again in the future.
> #1061: fixed test and cover all OS (red/green pattern)

- cli/src/test/java/com/devonfw/tools/ide/merge/XmlMergerTest.java
- cli/src/test/resources/xmlmerger/advanced/result.xml
- cli/src/test/resources/xmlmerger/advanced/target.xml
- cli/src/test/resources/xmlmerger/advanced/template.xml
Implements:
* made sure that XmlMerger tests will fail on errors
> Improve XmlMergerTest to fail on errors

- cli/src/main/java/com/devonfw/tools/ide/os/WindowsHelperImpl.java
> #1093: do not fail on remove of variable if not defined

- windows-installer/Package.wxs
fixes #1111 
after PR #1120 was still buggy, it is now working
> #1111: fix mkdir

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/commandlet/StatusCommandlet.java
fixes #1153
* print os info in "ide status"
> #1153: print os info in status

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java
fixes #1086
delete ide download cache on uninstall
> #1086: delete ide download cache on uninstall

- cli/pom.xml
- cli/src/main/java/com/devonfw/tools/ide/cli/GraalVmHelper.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/InstallCommandlet.java
- pom.xml
fixes #1084
properly detect basedir of IDEasy installation from graalvm native image
> #1084: properly detect IDEasy installation dir from native image

- cli/src/main/package/functions
- documentation/cli.adoc
fixes #889 
* improve icd (e.g. to support both `-p` and `-w` together, but also `-h` and long-options)
* added documentation
> #889: improve icd command

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/git/GitContextImpl.java
Fixes: #1202
**Implements**
* fallback to master if branch name was null
> #1202: Added branchname fallback to master

- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/tool/IdeasyCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/test/java/com/devonfw/tools/ide/tool/IdeasyCommandletTest.java
fixes #1208 
* write the version file to create a consistent installation on install of IDEasy.
* extend test to verify the version file is properly created.
> #1208: #1231: write version file on installation

- cli/src/test/integration-tests/install-intellij.sh
Fixes: #1290
**Implements**
* adjusted path for intellij on Mac
* Result can be seen here: https://github.com/jan-vcapgemini/IDEasy/actions/runs/14879788503
> #1290: Fixed intellij test on Mac

- .github/PULL_REQUEST_TEMPLATE.md
* Removed confusing quotation marks around issue ID
---
> #1199: Removed confusing quotation marks around issue ID

- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
* changed graalvm-community version from 23.0.2 to 21.0.2
* fixed linux architecture problem
> #1038: Fixed linux native build not working

- CHANGELOG.adoc
* Update changelog
* Fix inconsistencies and typos
---
> Update changelog and fix inconsistencies and typos

- url-updater/src/main/java/com/devonfw/tools/ide/url/tool/java/JavaUrlUpdater.java
- url-updater/src/test/java/com/devonfw/tools/ide/url/tool/java/JavaUrlUpdaterTest.java
* Added java mac arm64 urls
* adjusted tests to check for mac_arm64 urls and checksums too
---
> #1379: add mac arm java urls

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccess.java
- cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java
* Set writeable permission for file before deleting
---
> #1304: Fix VSCode reinstall error

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/commandlet/CreateCommandlet.java
* Checks for a potential file starting with "welcome." and logs its content on info level
---
> #1292: logs potential welcome file to info level

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/gradle/Gradle.java
- cli/src/main/java/com/devonfw/tools/ide/tool/mvn/Mvn.java
- cli/src/test/java/com/devonfw/tools/ide/tool/gradle/GradleTest.java
- cli/src/test/java/com/devonfw/tools/ide/tool/mvn/MvnTest.java
- cli/src/test/resources/ide-projects/gradle/repository/gradle/gradle/default/bin/gradlew
* added gradlew detection (copied from mvn)
* added test for gradlew detection
* added gradlew file to gradle test repository
* added gradle.build.kts file check to Gradle
* added Predicate checks as argument to findWrapper method
---
> #1372: Add gradle wrapper support

- cli/src/main/java/com/devonfw/tools/ide/commandlet/AbstractUpdateCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/commandlet/CreateCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeContextConsole.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeStartContext.java
- cli/src/main/java/com/devonfw/tools/ide/context/IdeStartContextImpl.java
- cli/src/main/java/com/devonfw/tools/ide/git/GitUrl.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/RepositoryCommandletTest.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/UpdateCommandletTest.java
- cli/src/test/java/com/devonfw/tools/ide/context/AbstractIdeTestContext.java
- cli/src/test/java/com/devonfw/tools/ide/context/IdeTestContext.java
- cli/src/test/java/com/devonfw/tools/ide/tool/plugin/PluginBasedCommandletTest.java
- gui/src/main/java/com/devonfw/ide/gui/IdeGuiContext.java
* simplify code in AbstractUpdateCommandlet and subclasses
* cleanup askForInput
* fixed broken JavaDoc
* removed pointless code
---
> #742: code cleanup and simplification

- CHANGELOG.adoc
- cli/src/main/java/com/devonfw/tools/ide/merge/xml/XmlMergeSupport.java
- cli/src/test/resources/xmlmerger/id-fallback/result.xml
- cli/src/test/resources/xmlmerger/id-fallback/target.xml
- cli/src/test/resources/xmlmerger/id-fallback/template.xml
* changed test to reveal bug
* fixed bug
* added to CHANGELOG
---
> #1451: fix merge:id default for single attribute

- cli/src/main/java/com/devonfw/tools/ide/cache/CachedValue.java
- cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java
- cli/src/test/java/com/devonfw/tools/ide/cache/CachedValueTest.java
* added `CachedValue`
* use `CachedValue` in `NpmBasedCommandlet` to avoid overhead of repeated process exectuion
* added `CachedValueTest`
---
> introduce CachedValue to prevent overhead of repeated process exectuion

- cli/src/main/java/com/devonfw/tools/ide/property/Property.java
- cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/ToolCommandlet.java
- cli/src/main/java/com/devonfw/tools/ide/tool/npm/NpmBasedCommandlet.java
- cli/src/test/java/com/devonfw/tools/ide/commandlet/InstallCommandletTest.java
- cli/src/test/java/com/devonfw/tools/ide/tool/npm/NpmTest.java
- cli/src/test/resources/ide-projects/basic/_ide/urls/java/java/21.0.8_9/linux_x64.urls
- cli/src/test/resources/ide-projects/basic/_ide/urls/java/java/21.0.8_9/mac_x64.urls
- cli/src/test/resources/ide-projects/basic/_ide/urls/java/java/21.0.8_9/windows_x64.urls
* fix reuse software from repo
---
> #1491: fix reuse software from repo
